const {BinarySearchTree}=require('./binary-search-tree') 
let binarySearchTree=new BinarySearchTree()
binarySearchTree.insert(41,41)
binarySearchTree.insert(22,22)
binarySearchTree.insert(58,58)
binarySearchTree.insert(15,15)
binarySearchTree.insert(33,33)
binarySearchTree.insert(50,50)
binarySearchTree.insert(60,60)
binarySearchTree.insert(13,13)
binarySearchTree.insert(37,37)
binarySearchTree.insert(42,42)
binarySearchTree.insert(53,53)
// console.log(binarySearchTree.root())
// console.log(binarySearchTree.contain(10))
// console.log(binarySearchTree.search(33))
// console.log(binarySearchTree.preOrder())
// console.log(binarySearchTree.inOrder())
// console.log(binarySearchTree.postOrder())
// console.log(binarySearchTree.levelOrder())
// console.log(binarySearchTree.minKey())
// console.log(binarySearchTree.maxKey())
console.log(binarySearchTree.remove(22))
console.log(binarySearchTree.levelOrder())
// binarySearchTree.insert(22,22)

